//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChangePassForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangePassForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ChangePassForm", typeof(ChangePassForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change your password?.
        /// </summary>
        public static string ChangePassQuestion {
            get {
                return ResourceManager.GetString("ChangePassQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Password.
        /// </summary>
        public static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageboxErrorCaption {
            get {
                return ResourceManager.GetString("MessageboxErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageboxQuestionCaption {
            get {
                return ResourceManager.GetString("MessageboxQuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter your new password!.
        /// </summary>
        public static string NewPassEmptyError {
            get {
                return ResourceManager.GetString("NewPassEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password must be between 5-25 characters!.
        /// </summary>
        public static string NewPassLengthError {
            get {
                return ResourceManager.GetString("NewPassLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot be the same as old password!.
        /// </summary>
        public static string NewPassRepeatError {
            get {
                return ResourceManager.GetString("NewPassRepeatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Password:.
        /// </summary>
        public static string NewPasswordLabelText {
            get {
                return ResourceManager.GetString("NewPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to confirm your old password first!.
        /// </summary>
        public static string OldPassEmptyError {
            get {
                return ResourceManager.GetString("OldPassEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password is not correct!.
        /// </summary>
        public static string OldPassNotCorrectError {
            get {
                return ResourceManager.GetString("OldPassNotCorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Old Password:.
        /// </summary>
        public static string OldPasswordTextboxText {
            get {
                return ResourceManager.GetString("OldPasswordTextboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password Has already been changed,
        ///Logging you out....
        /// </summary>
        public static string PassAlreadyChangedError {
            get {
                return ResourceManager.GetString("PassAlreadyChangedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully changed your Paasword!.
        /// </summary>
        public static string PassChangedMessage {
            get {
                return ResourceManager.GetString("PassChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must re-enter your new password!.
        /// </summary>
        public static string RepeatPassEmptyError {
            get {
                return ResourceManager.GetString("RepeatPassEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter your new password correctly!.
        /// </summary>
        public static string RepeatPassNotCorrect {
            get {
                return ResourceManager.GetString("RepeatPassNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;epeat New
        ///Password:.
        /// </summary>
        public static string RepeatPasswordLabelText {
            get {
                return ResourceManager.GetString("RepeatPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        public static string ResetButtonText {
            get {
                return ResourceManager.GetString("ResetButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ret&amp;urn.
        /// </summary>
        public static string ReturnButtonText {
            get {
                return ResourceManager.GetString("ReturnButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
    }
}
