//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DataDictionary", typeof(DataDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string DisplayFullName {
            get {
                return ResourceManager.GetString("DisplayFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book&apos;s Description.
        /// </summary>
        public static string LocalBookDescription {
            get {
                return ResourceManager.GetString("LocalBookDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book&apos;s Name.
        /// </summary>
        public static string LocalBookName {
            get {
                return ResourceManager.GetString("LocalBookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book&apos;s Type.
        /// </summary>
        public static string LocalBookType {
            get {
                return ResourceManager.GetString("LocalBookType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book&apos;s Genre.
        /// </summary>
        public static string LocalGenre {
            get {
                return ResourceManager.GetString("LocalGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Privileges.
        /// </summary>
        public static string LocalIsActive {
            get {
                return ResourceManager.GetString("LocalIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Privileges.
        /// </summary>
        public static string LocalIsAdmin {
            get {
                return ResourceManager.GetString("LocalIsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Admin Privileges.
        /// </summary>
        public static string LocalIsSysAdmin {
            get {
                return ResourceManager.GetString("LocalIsSysAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LocalPasswordName {
            get {
                return ResourceManager.GetString("LocalPasswordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Year.
        /// </summary>
        public static string LocalPublishYear {
            get {
                return ResourceManager.GetString("LocalPublishYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Description.
        /// </summary>
        public static string LocalUserDescription {
            get {
                return ResourceManager.GetString("LocalUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LocalUsername {
            get {
                return ResourceManager.GetString("LocalUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s Name.
        /// </summary>
        public static string LocalWriterName {
            get {
                return ResourceManager.GetString("LocalWriterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book&apos;s Owner.
        /// </summary>
        public static string OwnerUser {
            get {
                return ResourceManager.GetString("OwnerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Id.
        /// </summary>
        public static string OwnerUserId {
            get {
                return ResourceManager.GetString("OwnerUserId", resourceCulture);
            }
        }
    }
}
