//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LoginForm", typeof(LoginForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        public static string exitButton {
            get {
                return ResourceManager.GetString("exitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure that you want to close the application?.
        /// </summary>
        public static string formClosingMessage {
            get {
                return ResourceManager.GetString("formClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string formClosingMessageCaption {
            get {
                return ResourceManager.GetString("formClosingMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Login.
        /// </summary>
        public static string loginButton {
            get {
                return ResourceManager.GetString("loginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginFormText {
            get {
                return ResourceManager.GetString("LoginFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have successfully logged in!.
        /// </summary>
        public static string LoginSuccessfulMessage {
            get {
                return ResourceManager.GetString("LoginSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageboxCaption {
            get {
                return ResourceManager.GetString("MessageboxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        public static string passwordLabel {
            get {
                return ResourceManager.GetString("passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter your password!.
        /// </summary>
        public static string PasswordTextboxErrorMessage {
            get {
                return ResourceManager.GetString("PasswordTextboxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot be shorter than 5 or longer than 25 characters!.
        /// </summary>
        public static string PasswordTextboxLengthError {
            get {
                return ResourceManager.GetString("PasswordTextboxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Register.
        /// </summary>
        public static string registerButton {
            get {
                return ResourceManager.GetString("registerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re&amp;set.
        /// </summary>
        public static string resetButton {
            get {
                return ResourceManager.GetString("resetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username or password cannot contain empty spaces!.
        /// </summary>
        public static string TextboxWhitespaceError {
            get {
                return ResourceManager.GetString("TextboxWhitespaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Username:.
        /// </summary>
        public static string usernameLabel {
            get {
                return ResourceManager.GetString("usernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter your username!.
        /// </summary>
        public static string UsernameTextboxErrorMessage {
            get {
                return ResourceManager.GetString("UsernameTextboxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username cannot be shorter than 3 or longer than 20 characters!.
        /// </summary>
        public static string UsernameTextboxLengthError {
            get {
                return ResourceManager.GetString("UsernameTextboxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Username/Password is incorrect!.
        /// </summary>
        public static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
    }
}
