//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string ExitToolStripMenuItemText {
            get {
                return ResourceManager.GetString("ExitToolStripMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        public static string FirstPageButtonText {
            get {
                return ResourceManager.GetString("FirstPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        public static string LastPageButtonText {
            get {
                return ResourceManager.GetString("LastPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Library Management.
        /// </summary>
        public static string MainFormText {
            get {
                return ResourceManager.GetString("MainFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string NextPageButtonText {
            get {
                return ResourceManager.GetString("NextPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        public static string PageLabelText {
            get {
                return ResourceManager.GetString("PageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string PreviousPageButtonText {
            get {
                return ResourceManager.GetString("PreviousPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Search.
        /// </summary>
        public static string SearchBookButtonText {
            get {
                return ResourceManager.GetString("SearchBookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Aut&amp;hor:.
        /// </summary>
        public static string SearchByAuthorLabelText {
            get {
                return ResourceManager.GetString("SearchByAuthorLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Book Ty&amp;pe:.
        /// </summary>
        public static string SearchByBookTypeLabelText {
            get {
                return ResourceManager.GetString("SearchByBookTypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By &amp;Genre:.
        /// </summary>
        public static string SearchByGenreLabelText {
            get {
                return ResourceManager.GetString("SearchByGenreLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By &amp;Name:.
        /// </summary>
        public static string SearchByNameLabelText {
            get {
                return ResourceManager.GetString("SearchByNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By O&amp;wner Username:.
        /// </summary>
        public static string SearchByOwnerUsernameLabelText {
            get {
                return ResourceManager.GetString("SearchByOwnerUsernameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By &amp;Year:.
        /// </summary>
        public static string SearchByYearLabelText {
            get {
                return ResourceManager.GetString("SearchByYearLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show A&amp;ll Books.
        /// </summary>
        public static string ShowAllBooksButtonText {
            get {
                return ResourceManager.GetString("ShowAllBooksButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Books.
        /// </summary>
        public static string ToolStripAdminBooksItemText {
            get {
                return ResourceManager.GetString("ToolStripAdminBooksItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Admin.
        /// </summary>
        public static string ToolStripAdminOptionText {
            get {
                return ResourceManager.GetString("ToolStripAdminOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ToolStripAdminUsersItemText {
            get {
                return ResourceManager.GetString("ToolStripAdminUsersItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add A New Book.
        /// </summary>
        public static string ToolStripBookAddItemText {
            get {
                return ResourceManager.GetString("ToolStripBookAddItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Your Books.
        /// </summary>
        public static string ToolStripBookManageItemText {
            get {
                return ResourceManager.GetString("ToolStripBookManageItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Unwanted Book.
        /// </summary>
        public static string ToolStripBookOwnItemText {
            get {
                return ResourceManager.GetString("ToolStripBookOwnItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Books.
        /// </summary>
        public static string ToolStripBooksOptionText {
            get {
                return ResourceManager.GetString("ToolStripBooksOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalize Colours.
        /// </summary>
        public static string ToolStripColorSettingItem {
            get {
                return ResourceManager.GetString("ToolStripColorSettingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Application.
        /// </summary>
        public static string ToolStripExitItemText {
            get {
                return ResourceManager.GetString("ToolStripExitItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string ToolStripLogoutItemText {
            get {
                return ResourceManager.GetString("ToolStripLogoutItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;ettings.
        /// </summary>
        public static string ToolStripSettingOptionText {
            get {
                return ResourceManager.GetString("ToolStripSettingOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Password.
        /// </summary>
        public static string ToolStripUserChangePassItemText {
            get {
                return ResourceManager.GetString("ToolStripUserChangePassItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;User Setting.
        /// </summary>
        public static string ToolStripUserOptionText {
            get {
                return ResourceManager.GetString("ToolStripUserOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Your Profile.
        /// </summary>
        public static string ToolStripUserUpdateItemText {
            get {
                return ResourceManager.GetString("ToolStripUserUpdateItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}! You are logged in as {1}.
        /// </summary>
        public static string UserWelcomeMessageText {
            get {
                return ResourceManager.GetString("UserWelcomeMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string YearFromLabelText {
            get {
                return ResourceManager.GetString("YearFromLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string YearToLabelText {
            get {
                return ResourceManager.GetString("YearToLabelText", resourceCulture);
            }
        }
    }
}
